Vagrant.configure("2") do |config|
#centOS 6 node
  config.vm.define :centos6 do |centos6|
  centos6.vm.box = "puppetlabs/centos-6.6-64-puppet"
  centos6.vm.hostname = 'centos6'
  centos6.vm.network "forwarded_port", guest: 80, host: 8081
  end
#ubuntu 14 node
  config.vm.define :ubuntu14 do |ubuntu14|
  ubuntu14.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
  ubuntu14.vm.hostname = 'ubuntu14'
  ubuntu14.vm.network "forwarded_port", guest: 80, host: 8082
  end
end
