Vagrant.configure("2") do |config|
  #centOS 7 node
  config.vm.define :centos7 do |centos7|
    centos7.vm.box = "puppetlabs/centos-7.0-64-puppet"
    centos7.vm.hostname = 'centos7'
    centos7.vm.network "forwarded_port", guest: 80, host: 8081
  end
end
